# Generated by Django 5.1.7 on 2025-04-30 05:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outfit',
            name='category',
            field=models.CharField(choices=[('casual', 'Casual'), ('classy', 'Classy'), ('formal', ' Formal'), ('sporty', 'Sporty'), ('vintage', 'Vintage'), ('other', 'Other')], max_length=20),
        ),
    ]
